#!/usr/bin/env bash
set -e

echo "== create vpc =="

TAG="my-vpc-123"

# Create VPC
VPC_ID=$(aws ec2 create-vpc \
    --cidr-block 172.1.0.0/16 \
    --region eu-west-2 \
    --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=$TAG-vpc}]" \
    --query Vpc.VpcId \
    --output text)

echo "VPC_ID: $VPC_ID"
echo "VPC_NAME: $TAG-vpc"

# Enable DNS hostnames for VPC
aws ec2 modify-vpc-attribute \
    --vpc-id $VPC_ID \
    --enable-dns-hostnames "{\"Value\":true}"

# Create IGW
IGW_ID=$(aws ec2 create-internet-gateway \
    --tag-specifications "ResourceType=internet-gateway,Tags=[{Key=Name,Value=$TAG-igw}]" \
    --query InternetGateway.InternetGatewayId \
    --output text)

echo "IGW_ID: $IGW_ID"

# Attach IGW
aws ec2 attach-internet-gateway \
    --internet-gateway-id $IGW_ID \
    --vpc-id $VPC_ID

echo "Attached IGW to VPC"

# Create Subnets
SUBNET_ID=$(aws ec2 create-subnet \
    --vpc-id $VPC_ID \
    --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=$TAG-subnet}]" \
    --cidr-block 172.1.0.0/20 \
    --query Subnet.SubnetId \
    --output text)

echo "SUBNET_ID: $SUBNET_ID"

# Auto-assign ipv4 to Subnet
aws ec2 modify-subnet-attribute \
    --subnet-id $SUBNET_ID \
    --map-public-ip-on-launch

# Associate subnet
RT_ID=$(aws ec2 describe-route-tables \
    --filters "Name=vpc-id,Values=$VPC_ID" \
    --query RouteTables[0].RouteTableId \
    --output text)

echo "RT_ID: $RT_ID"

aws ec2 associate-route-table \
    --route-table-id $RT_ID \
    --subnet-id $SUBNET_ID

echo "Subnet associated with Route Table"

# Add route for IGW
aws ec2 create-route \
    --route-table-id $RT_ID \
    --destination-cidr-block 0.0.0.0/0 \
    --gateway-id $IGW_ID

echo "Route for IGW added to Route Table"