#!/usr/bin/env bash
set -e

echo "== delete vpc =="

if [ -z "$1" ]; then
    echo "VPC ID must be provided."
    exit 1
fi

VPC_ID=$1
echo "VPC_ID: $VPC_ID"

RT_ID=$(aws ec2 describe-route-tables \
    --filters "Name=vpc-id,Values=$VPC_ID" \
    --query RouteTables[0].RouteTableId \
    --output text)
echo "RT_ID: $RT_ID"

IGW_ID=$(aws ec2 describe-internet-gateways \
    --filters "Name=attachment.vpc-id,Values=$VPC_ID" \
    --query InternetGateways[0].InternetGatewayId \
    --output text)
echo "IGW_ID: $IGW_ID"

SUBNET_ID=$(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$VPC_ID" \
    --query Subnets[0].SubnetId \
    --output text)
echo "SUBNET: $SUBNET_ID"

RT_ASSOC_ID=$(aws ec2 describe-route-tables \
    --filters "Name=association.subnet-id,Values=subnet-0d467fc14cb259249" \
    --query "RouteTables[*].Associations[?SubnetId=='subnet-0d467fc14cb259249'].RouteTableAssociationId" \
    --output text)

# Dissasociate non-main RT
if [ -z "$RT_ASSOC_ID" ]; then
    aws ec2 disassociate-route-table --association-id $RT_ASSOC_ID
    echo "Deleting explicit route tables"
fi

# Delete subnets
aws ec2 delete-subnet --subnet-id $SUBNET_ID

echo "Deleting subnets"

# Delete custom routes
aws ec2 delete-route \
    --route-table-id $RT_ID \
    --destination-cidr-block 0.0.0.0/0

echo "Deleting custom routes"

# Detach IGW from VPC
aws ec2 detach-internet-gateway \
    --internet-gateway-id $IGW_ID \
    --vpc-id $VPC_ID

echo "Detached IGW from VPC"

# Delete IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

echo "Deleted IGW"

# Delete VPC
aws ec2 delete-vpc --vpc-id $VPC_ID

echo "Deleted VPC"