#!/usr/bin/env bash
echo "== create bucket =="

if [ -z "$1" ]; then
    echo "A bucket name must be provided."
    exit 1
fi

if [ -z "$2" ]; then
    echo "A bucket region must be provided."
    exit 1
fi

BUCKET_NAME=$1
REGION=$2

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
 --bucket $BUCKET_NAME \
 --create-bucket-configuration="LocationConstraint=$REGION" \
 --query Location \
 --output text