#!/usr/bin/env bash
echo "== delete bucket =="

if [ -z "$1" ]; then
    echo "A bucket name must be provided."
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
aws s3api delete-bucket \
 --bucket $BUCKET_NAME \