#!/usr/bin/env bash
echo "== list buckets =="

# https://docs.aws.amazon.com/cli/latest/reference/s3-api/list-buckets.html
aws s3api list-buckets \
 --query Buckets[*].Name \
 --output text | tr '\t' '\n'