#!/usr/bin/env bash
echo "== put object =="

if [ -z "$1" ]; then
    echo "A bucket name must be provided."
    exit 1
fi

if [ -z "$2" ]; then
    echo "A name for the file/object must be provided."
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2
OBJECT_KEY=$(basename "$FILE_NAME")

# https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html
aws s3api put-object \
 --bucket $BUCKET_NAME \
 --body $FILE_NAME \
 --key $OBJECT_KEY \
 --query ETag \
 --output text | tr -d '"'