#!/usr/bin/env bash
echo "== sync =="

if [ -z "$1" ]; then
    echo "Source directory/file for sync must be provided."
    exit 1
fi

if [ -z "$2" ]; then
    echo "Destination bucket for sync must be provided."
    exit 1
fi

SOURCE=$1
DEST=$2

# https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html
aws s3 sync \
 $SOURCE \
 "s3://$DEST/files"